# Generated by Django 4.1.7 on 2023-04-20 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='reference',
            field=models.CharField(default='Order-Ref: K1S3AzagcV43O5klsatN', editable=False, max_length=50, unique=True),
        ),
    ]
