# Generated by Django 4.1.7 on 2023-04-22 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_orders_reference_addresses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addresses',
            name='zip',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='reference',
            field=models.CharField(default='Order-Ref: rMnVtgdwskuJrSLqK6Re', editable=False, max_length=50, unique=True),
        ),
    ]
