# Generated by Django 4.1.7 on 2023-04-22 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_addresses_zip_alter_orders_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addresses',
            name='city',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='addresses',
            name='others',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='addresses',
            name='state',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='reference',
            field=models.CharField(default='Order-Ref: 86Lt4zmmWUgDgeJiqCCp', editable=False, max_length=50, unique=True),
        ),
    ]
