# Generated by Django 4.1.7 on 2023-04-24 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_alter_cart_address_alter_orders_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='reference',
            field=models.CharField(default='Order-Ref: NLCkeTPhlYNQMWYw9by1', editable=False, max_length=50, unique=True),
        ),
    ]
